[

	
	"Adventist University of Africa" =>"Adventist University of Africa",
	"Africa International University" =>"Africa International University",
	"Africa Nazarene University" =>"Africa Nazarene University",
	"Catholic University of Eastern Africa" =>"Catholic University of Eastern Africa",
	"Chuka University" =>"Chuka University",
	"Daystar University" =>"Daystar University",
	"Dedan Kimathi University of Technology" =>"Dedan Kimathi University of Technology",
	"Egerton University" =>"Egerton University",
	"Great Lakes University of Kisumu" =>"Great Lakes University of Kisumu",
	"Gretsa University" =>"Gretsa University",
	"Inoorero University" =>"Inoorero University",
	"Jaramogi Oginga Odinga University of Science and Technology" =>"Jaramogi Oginga Odinga University of Science and Technology",
	"Jomo Kenyatta University of Agriculture and Technology" =>"Jomo Kenyatta University of Agriculture and Technology",
	"Kabarak University" =>"Kabarak University",
	"Karatina University" =>"Karatina University",
	"KCA University" =>"KCA University",	
	"Kenya Highlands Evangelical University" =>"Kenya Highlands Evangelical University",
	"Kenya Methodist University" =>"Kenya Methodist University",
	"Kenyatta University" =>"Kenyatta University",
	"Kiriri Women's University of Science and Technology" =>"Kiriri Women's University of Science and Technology",
	"Kisii University" =>"Kisii University",
	"Laikipia University" =>"Laikipia University",
	"Maasai Mara University" =>"Laikipia University",
	"Management University of Africa" =>"Management University of Africa",
	"Maseno University" =>"Maseno University",
	"Masinde Muliro University of Science and Technology" =>"Masinde Muliro University of Science and Technology",
	"Meru University of Science and Technology" =>"Meru University of Science and Technology",
	"Moi University" =>"Moi University",
	"Mount Kenya University" =>"Mount Kenya University",
	"Multimedia University of Kenya" =>"Multimedia University of Kenya",
	"Pan Africa Christian University" =>"Pan Africa Christian University,",
	"Pwani University"=>"Pwani University",
	"South Eastern Kenya University" =>"South Eastern Kenya University",
	"St. Paul's University"	=>"St. Paul's University",
	"Strathmore University"	=>"Strathmore University",
	"Technical University of Kenya"	=>"Technical University of Kenya",
	"Technical University of Mombasa" =>"Technical University of Mombasa",
	"The East African University" =>"The East African University",
	"The Presbyterian University of East Africa" =>"The Presbyterian University of East Africa",
	"United States International University" =>"United States International University",
	"University of Eastern Africa, Baraton"	=>"University of Eastern Africa, Baraton",
	"University of Eldoret"	=>"University of Eldoret",
	"University of Nairobi"	=>"University of Nairobi"


];
